### ISSUE TITLE
allow unit test reports to be picked up for the superset tool

### ISSUE THREAD

**Issue by vroubtsovTT** [tenstorrent/tt-mlir#3624]
A suggestion made for #3583 was to comply with the artifact rules used by the `superset` tooling:

- make sure "report" is in the artifact name (I think this is the case already)
- add a CI job ID suffix to the artifact name

This applies to one or two artifacts:

(1) the `report.xml` output into `${{ steps.strings.outputs.build-output-dir }}/test/report.xml` by the `check-ttmlir` cmake target of "Check" and uploaded as "check_test_report.xml"
```yaml
    - name: Check
      id: check
      shell: bash
      run: |
        source env/activate
        lcov --directory ${{ steps.strings.outputs.build-output-dir }} --capture --initial --output-file baseline.info --gcov-tool ${{ steps.strings.outputs.work-dir }}/.github/workflows/gcov_for_clang.sh
        # this will output `test/report.xml` in the build dir:
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --target check-ttmlir

    - name: Upload Check Test Report xml
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: check_test_report.xml
        path: ${{ steps.strings.outputs.build-output-dir }}/test/report.xml
        if-no-files-found: 'ignore'
```
(2) reports output into `${{ steps.strings.outputs.test_report_path }}` by direct `llvm-lit ... test` invocation in "Generate tests" and further processed/merged?... this one is not new, I am not sure of everything that happens to it

```yaml
    - name: Generate tests
      shell: bash
      run: |
        source env/activate
        export LD_LIBRARY_PATH="${{ steps.strings.outputs.install-output-dir }}/lib:${TTMLIR_TOOLCHAIN_DIR}/lib:${LD_LIBRARY_PATH}"
        export SYSTEM_DESC_PATH="${GITHUB_WORKSPACE}/ttrt-artifacts/system_desc.ttsys"
        ln -sf ${{ steps.strings.outputs.install-output-dir }} ${{ steps.strings.outputs.build-output-dir }}
        llvm-lit -v --xunit-xml-output ${{ steps.strings.outputs.test_report_path }} ${{ steps.strings.outputs.build-output-dir }}/test
```
